name: 'bts-get-content'
description: 'get content from repo for specific path'
author: BTSavvy
branding:
  icon: box
  color: orange
inputs:
  owner:
    description: 'The owner of the repo'
    required: true
  repo_name:
    description: 'The name of the repo'
    required: true
  branch_name:
    description: 'The branch name of the repo'
    required: true
  path_name:
    description: 'The path name'
    required: true
  placeholder_attributes:
    description: 'The list of attributes in the files that you like to substitute, if  enter ATTRIBUTE=VALUE, ATTRIBUTE:VALUE  for {{{ATTRIBUTE}}}, for list use comma delimitation   '
    required: false
  token:
    description: 'The github app token'
    required: true
outputs:
  data:
    description: 'The placeholder for any output data'
runs:
  using: 'docker'
  image: 'docker://btsavvy/action-get-content:latest'